### PR TITLE
Requireish

### PR DESCRIPTION
**Pull request by jwalton**
@kamekazemaster have a read through this - it's based on your changes, but I'm trying to read the "requireish" from the config instead of forcing it to be specified programatically.  I feel quite sure that I'm missing something here.  -_-  But see what you think.  :)

### CODE REVIEW

**Comment by jwalton** [comment]
This breaks a little bit in that you can no longer call "setConfig()", but I'm happy to deprecate that and bump the major version.  I'm happy to remove "configure()" for that matter, now that you can just pass configuration directly to a transform.  :P

**Comment by kamekazemaster** [comment]
I just have thought about the same alternative way to implement it like you did :D 

I had the idea to make it like for example babelify which loads a .babelrc file as config. Alternatively (or additionally?) pass in configuration alá .transform(aliasify.configure({...}). 

Some notices to your implementation:
I think you should merge the two configs passed in in the case where you call configure() and have a config file. The passed in one through .configure() with higher priority.

I don't completely understand how transformTools.loadTransformConfigSync does find your actual config file. Did I get it right that you have to set the path to your config file in the package.json? Wouldn't it be better to determine a static name required for the config file? (like babel's .babelrc file)

Another thing is that you don't pass requireish strings which should **additionally** be aliased instead you have to state all of them. I think your solution is better but this have to be changed in the doc also ;)

**Comment by jwalton** [comment]
> I think you should merge the two configs passed in in the case where you call configure() and have a config file. The passed in one through .configure() with higher priority.

We actually will end up merging them - you'll note we only extract `requireish` [here](https://github.com/benbria/aliasify/blob/6451e376c78e0e5cb227fa7205890aa769a55ed7/src/aliasify.coffee#L101-L106) and ignore everything else.  We also load it from `config` if there is a `requireish` in config, and otherwise we go load from package.json, even if `config` was passed in (so if both `config` and package.json have a `requireish`, we take the config one.)  But then at the end, we pass `config` into `wrappedTransform`, and down in browserify-transform-tools, it will [merge them before we get into the real stuff](https://github.com/benbria/browserify-transform-tools/blob/64ca9bfa60b8242a4d1c9dbef603f003f46e6ccd/src/transformTools.coffee#L74).

> I don't completely understand how transformTools.loadTransformConfigSync does find your actual config file. Did I get it right that you have to set the path to your config file in the package.json? Wouldn't it be better to determine a static name required for the config file? (like babel's .babelrc file)

I've never been a huge fan of loading out of package.json, but I stole it from somewhere else - I think from thlorenz/browserify-shim?  When I wrote browserify-transform-tools, there was no nice way to pass parameters to a transform, and substack seemed to initially be against the idea of passing them as a second parameter to the transform function (like they are now.)  That's by far the cleanest way to do it, though - you can do it programatically, and you can even pass them on the command line now:

    browserify -t [ aliasify --requireish proxyquire ]

for example (I have no idea if I can specify `requireish` more than once to make an array - I should figure that out and add an example to the README.md.  :) )

I'd be perfectly happy to deprecate loading from package.json from browserify-transform-tools, but it's a "thing" now, and people do it, and I'd break everything.  :P

To answer your question more directly - you can either put the config straight into package.json, so have a section in package.json that looks like:

    aliasify: {
        requireish: ['proxyquire']
        ...
    }

Or you can specify a path to a JS config file (which is nicer, because then you can use variables and such.)

> Another thing is that you don't pass requireish strings which should additionally be aliased instead you have to state all of them. I think your solution is better but this have to be changed in the doc also ;)

Good point.  I will fix this.  :)

**Comment by jwalton** [comment]
TODO:

* [ ] Document that you need to explicitly pass `require` in `requireish` if you want it to do what you think it should do.
* [ ] Work out the best way to pass an array of values from the browserify command line, and document this.

**Comment by jwalton** [comment]
If you want to read more about how browserify-transform-tools loads configuration, there's a lot of details here: https://github.com/benbria/browserify-transform-tools/wiki/Transform-Configuration

**Comment by jwalton** [comment]
I guess there's not really a great way to pass a list of aliases on the command line.  -_-  I mean, we could come up with something...  But, for future reference, if you do:

    browserify -t [ aliasify --requireish proxyquire ]

then aliasify will get passed a `config` of `'proxyquire'`, and if you do:

    browserify -t [ aliasify --requireish proxyquire --requireish foo ]

then aliasify will get passed a `config` of `['proxyquire', 'foo']`.  So we're halfway there.  :)  But we'd need to do something like: `--alias foo:bar` to pass aliases, which is out of scope of this PR for sure.  :)

**Comment by jwalton** [comment]
Published as v2.0.0.  Sorry again this took so long.  Let me know if you run into any problems.  :)

**Pull request merged**
